### ISSUE TITLE
Pass.lst not generated

### ISSUE THREAD

**Issue by frootydavid** [Pure-L0G1C/PassGen#3]
Dear,
pass.lst is not generated. are there any pre-requisite to open passgen.py file? any setting required?

**Comment by Pure-L0G1C** [comment]
just rename the output file to pass.lst

**Comment by frootydavid** [comment]
but where is the output file? i cant find it either

**Comment by frootydavid** [comment]
command python passGen.py is not executable.
It shows error Traceback (most recent call last):

  File "passGen.py", line 7, in <module>
    from src.update import Update
  File "C:\Users\Downloads\PassGen-master\src\update.py", line 80
    print '\n Searching for an update ...'
                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('\n Searching for an update ...')?

**Comment by Pure-L0G1C** [comment]
That is written in Python 2.7 and you’re using Python 3

**Comment by frootydavid** [comment]
Dear,
I did the same on python 2.7 version today. its the same. Kindly advise
